### PR TITLE
Embedded HTML bug fix. And support multilingual(unicode)

### PR DESCRIPTION
**Pull request by ghost**
I'm solve markdown renderer messes with embedded HTML bug.

In addition, Support non-alphabetic languages.

You can see a live demo [here](http://yangpro.github.io/showdown_typography/).

### CODE REVIEW

**Comment by halfdan** [comment]
Hi @yangpro 
I added a number of comments to your commits. It would be nice if you could clean up the code before this gets merged.

@caerphoto It would be great to have this land since we can use it to fix a number of issues in Ghost. You could then also publish it to bower (http://bower.io/).

**Comment by ghost** [comment]
Hi @halfdan 
I think I broke a few rules .
I'm weak in English. And beginner in github. Please understand.

Some modifications had to commit.
Comment again please.

**Comment by ghost** [comment]
@halfdan One kind of curious. This library follows the MIT license. 

MIT license:
1. This software is free to anyone, without limitation, may be treated. However, the display of the copyright notice and this permission copies of all or a major portion of the software should be described. 
2. Author or Author is not responsible for any software, it comes. 

Asked did not know. I broke the rules what does?
Please let me know. Thanks :)

(Translate via google translate)

**Comment by ErisDS** [comment]
HI @yangpro The rules in the license allow you to fork the repository and do as you wish with it. 

However, you wanted to merge those changes into Ghost, and Ghost is working with @caerphoto's original repo - so to get the changes accepted in Ghost they should be here (unless @caerphoto stops maintaining his repo).

You have fixed several issues, which is great, but you have also made a lot of changes to the readme, added build tools, and other things which do not belong in this PR.

This PR needs to just fix the bugs with tests - keep it as simple as possible.

Adding build tools, travis etc, ought to be a separate PR.

**Comment by ghost** [comment]
Oh, I'm fully understand now
Thanks @ErisDS 

Is there anything more to modify?

**Comment by ghost** [comment]
One more question @ErisDS
What does PR abbreviation for?

**Comment by ErisDS** [comment]
Sorry, I don't understand you and I don't think you understand me :(

**Comment by ghost** [comment]
Sorry, I was over enthusiastic. :)

**Comment by ErisDS** [comment]
Please make a clean Pull Request with only the bug fixes and related test changes.

**Comment by ghost** [comment]
Thanks :)

**Comment by caerphoto** [comment]
Sorry for the delay @ErisDS, I've been away all weekend. PR accepted now. Thanks @yangpro for the fix – the HTML thing was a silly oversight which I should have noticed originally – I don't tend to use much HTML in my Markdown.

Incidentally, if/when in the future Ghost has its own Markdown parser, it might be worth using a post-HTML-generation typography... er... improver (?), using the text node extraction method I used here: http://andyf.me/js/fix_text.js I don't think it's a good fit for Showdown, since it's basically a separate thing and operates on the resulting DOM structure.

**Pull request merged**
